--- #YAML:1.0
name:                Perl-Critic-Bangs
version:             0.22
abstract:            Perl::Critic::Bangs - A collection of policies for Perl::Critic
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Andy Lester <andy@petdance.com>
distribution_type:   module
requires:     
    Perl::Critic:                  0
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
